### ISSUE TITLE
코로나 명령어 NaN% 문제

### ISSUE THREAD

**Issue by arthur-yoon** [D3vle0/leo-bot#1]
안녕하세요. 좀 전에 디코로 추가를 해보았는데 사용중 버그가 있어서 이슈 제보합니다.

![image](https://user-images.githubusercontent.com/47406496/103662015-c4d50580-4fb2-11eb-8bc3-0f67842f9192.png)

**Comment by D3vle0** [comment]
사망자가 1000명을 넘어가며 찍힌 콤마 때문에 정수로 인식을 하지 않았던 문제입니다. 해결되었습니다 👍
